---
- name: Launch  new webserver
  ec2:
    aws_access_key: "{{ aws_id }}"
    aws_secret_key: "{{ aws_key }}"
    region: "{{ aws_region }}"
    image: ami-f2e6e58d 
    instance_type: t2.micro
    state: present
    vpc_subnet_id: subnet-d399f0dc
    assign_public_ip: yes
    group_id: sg-95e81cdf
    wait: yes
  register: ec2

- name: Add instances to a temporary host group stored in memory
  local_action: add_host name={{ item.public_dns_name }} groups=ec2_temp_group
  with_items: "{{ ec2.instances }}"

- name: Waiting for ssh port to open
  become: no
  local_action: wait_for host={{ item.public_dns_name }} port=22 state=started timeout=150
  with_items: "{{ ec2.instances }}"


