---
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Launch  new webserver
    ec2:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      image: ami-411e1e3e
      instance_type: t2.micro
      state: present
      vpc_subnet_id: subnet-d399f0dc
      assign_public_ip: yes
      group_id: sg-95e81cdf
