---
- hosts: aws
  remote_user: ubuntu
  become_method: sudo
  become: yes
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Gather info
    action: ec2_facts
  - name: Display instance type
    debug: msg='{{ansible_ec2_instance_type}}'
